//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrySwitch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gry
    {
        public int Id { get; set; }
        public string Tytuł { get; set; }
        public Nullable<int> Cena { get; set; }
        public int IdGatunku { get; set; }
        public Nullable<int> IdNagród { get; set; }
        public Nullable<System.DateTime> DataWydania { get; set; }
    
        public virtual Gatunki Gatunki { get; set; }
        public virtual Nagrody Nagrody { get; set; }
    }
}
